spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        auto_quote_keyword: true
        show_sql: true
        format_sql: true
        highlight_sql: true

    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

## ehcache 캐시 설정
  cache:
    jcache:
      config: classpath:ehcache.xml


logging:
  level:
    root: debug


shorten-url:
  default-char: "*"
  default-hash-length: 7
  allowed-protocols:
    - http://
    - https://
